"""
Django settings for LumSys project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

import os
from pathlib import Path


# =========================
# RUTAS DEL PROYECTO
# =========================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# CARGA DEL ARCHIVO .env
# =========================

def load_env_file(path):
    """
    Carga variables desde un archivo .env sin usar librerías externas.
    El archivo .env debe estar en la raíz del proyecto, junto a manage.py.
    """

    if not path.exists():
        return

    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()

        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)

        key = key.strip()
        value = value.strip().strip('"').strip("'")

        os.environ.setdefault(key, value)


def env_required(name):
    """
    Obtiene una variable obligatoria del entorno.
    Si no existe, detiene la ejecución del proyecto.
    """

    value = os.getenv(name)

    if value is None or value.strip() == "":
        raise RuntimeError(
            f"Falta configurar la variable {name} en el archivo .env"
        )

    return value


def env_bool(name, default=False):
    """
    Convierte variables tipo texto a booleano.
    Ejemplo:
    DEBUG=True -> True
    DEBUG=False -> False
    """

    value = os.getenv(name)

    if value is None:
        return default

    return value.lower() in ("1", "true", "yes", "on")


def env_list(name, default=None):
    """
    Convierte una variable separada por comas en una lista.
    Ejemplo:
    ALLOWED_HOSTS=localhost,127.0.0.1
    """

    value = os.getenv(name)

    if not value:
        return default or []

    return [
        item.strip()
        for item in value.split(",")
        if item.strip()
    ]


load_env_file(BASE_DIR / ".env")


# =========================
# CONFIGURACIÓN GENERAL
# =========================

SECRET_KEY = env_required("SECRET_KEY")

DEBUG = env_bool("DEBUG", False)

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    ["localhost", "127.0.0.1"]
)


# =========================
# APLICACIONES
# =========================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "Luminarias",
]


# =========================
# MIDDLEWARE
# =========================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================
# URLS Y WSGI
# =========================

ROOT_URLCONF = "LumSys.urls"

WSGI_APPLICATION = "LumSys.wsgi.application"


# =========================
# TEMPLATES
# =========================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =========================
# BASE DE DATOS
# =========================

DATABASES = {
    "default": {
        "ENGINE": env_required("DB_ENGINE"),
        "NAME": env_required("DB_NAME"),
        "USER": env_required("DB_USER"),
        "PASSWORD": env_required("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# =========================
# VALIDACIÓN DE CONTRASEÑAS
# =========================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# =========================
# INTERNACIONALIZACIÓN
# =========================

LANGUAGE_CODE = "es-sv"

TIME_ZONE = "America/El_Salvador"

USE_I18N = True

USE_TZ = True


# =========================
# ARCHIVOS ESTÁTICOS
# =========================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# =========================
# CONFIGURACIÓN FINAL
# =========================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"