# Generated by Django 6.0.5 on 2026-05-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_red', models.CharField(max_length=50)),
                ('voltaje', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'red',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('carnet', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Luminaria',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('potencia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estado', models.BooleanField()),
                ('tipo', models.CharField(max_length=1024)),
                ('red', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='luminarias', to='Luminarias.red')),
            ],
            options={
                'db_table': 'luminaria',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField()),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('usuario', models.ForeignKey(blank=True, db_column='carnet', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reportes', to='Luminarias.usuario')),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='ConsumoEnergia',
            fields=[
                ('codigo_consumo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('red', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='consumos', to='Luminarias.red')),
                ('usuario', models.ForeignKey(blank=True, db_column='carnet', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='consumos', to='Luminarias.usuario')),
            ],
            options={
                'db_table': 'consumo_energia',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('codigo_zona', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre_zona', models.CharField(max_length=50)),
                ('municipio', models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='zonas', to='Luminarias.municipio')),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='Contiene',
            fields=[
                ('pk', models.CompositePrimaryKey('red_id', 'zona_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('red', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.RESTRICT, related_name='zonas_asociadas', to='Luminarias.red')),
                ('zona', models.ForeignKey(db_column='codigo_zona', on_delete=django.db.models.deletion.RESTRICT, related_name='redes_asociadas', to='Luminarias.zona')),
            ],
            options={
                'db_table': 'contiene',
            },
        ),
    ]
