# Generated by Django 6.0.5 on 2026-05-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Luminarias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='red',
            old_name='id',
            new_name='id_red',
        ),
    ]
