# Generated by Django 6.0.5 on 2026-05-19 04:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luminarias', '0002_rename_id_red_id_red'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('roles', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ROL',
            },
        ),
        migrations.RemoveField(
            model_name='contiene',
            name='red',
        ),
        migrations.RemoveField(
            model_name='contiene',
            name='zona',
        ),
        migrations.RenameField(
            model_name='luminaria',
            old_name='codigo',
            new_name='id_luminaria',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='apellido_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='carnet',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='zona',
            old_name='codigo_zona',
            new_name='id_zona',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='usuario',
        ),
        migrations.AddField(
            model_name='luminaria',
            name='fecha_instalacion',
            field=models.DateField(default=datetime.date(2026, 5, 18)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='red',
            name='consumo_esperado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2026, 5, 18)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2026, 5, 18)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='formato',
            field=models.CharField(default='PDF', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zona',
            name='red',
            field=models.ForeignKey(blank=True, db_column='ID_RED', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='zonas', to='Luminarias.red'),
        ),
        migrations.AddField(
            model_name='zona',
            name='tipo_zona',
            field=models.CharField(default='Urbana', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='luminaria',
            name='potencia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='luminaria',
            name='red',
            field=models.ForeignKey(blank=True, db_column='ID_RED', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='luminarias', to='Luminarias.red'),
        ),
        migrations.AlterField(
            model_name='luminaria',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='red',
            name='voltaje',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo_reporte',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zona',
            name='municipio',
            field=models.ForeignKey(blank=True, db_column='ID_MUNICIPIO', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='zonas', to='Luminarias.municipio'),
        ),
        migrations.AlterModelTable(
            name='luminaria',
            table='LUMINARIA',
        ),
        migrations.AlterModelTable(
            name='municipio',
            table='MUNICIPIO',
        ),
        migrations.AlterModelTable(
            name='red',
            table='RED',
        ),
        migrations.AlterModelTable(
            name='reporte',
            table='REPORTE',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='USUARIO',
        ),
        migrations.AlterModelTable(
            name='zona',
            table='ZONA',
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('pk', models.CompositePrimaryKey('reporte_id', 'usuario_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('reporte', models.ForeignKey(db_column='ID_REPORTE', on_delete=django.db.models.deletion.RESTRICT, to='Luminarias.reporte')),
                ('usuario', models.ForeignKey(db_column='ID_USUARIO', on_delete=django.db.models.deletion.RESTRICT, to='Luminarias.usuario')),
            ],
            options={
                'db_table': 'REALIZA',
            },
        ),
        migrations.CreateModel(
            name='RegistrarLectura',
            fields=[
                ('id_lectura', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fecha_lectura', models.DateField()),
                ('consumo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variacion_consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('red', models.ForeignKey(blank=True, db_column='ID_RED', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lecturas', to='Luminarias.red')),
            ],
            options={
                'db_table': 'REGISTRARLECTURA',
            },
        ),
        migrations.CreateModel(
            name='Crea',
            fields=[
                ('pk', models.CompositePrimaryKey('usuario_id', 'lectura_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(db_column='ID_USUARIO', on_delete=django.db.models.deletion.RESTRICT, to='Luminarias.usuario')),
                ('lectura', models.ForeignKey(db_column='ID_LECTURA', on_delete=django.db.models.deletion.RESTRICT, to='Luminarias.registrarlectura')),
            ],
            options={
                'db_table': 'CREA',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, db_column='ID_ROL', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='Luminarias.rol'),
        ),
        migrations.DeleteModel(
            name='ConsumoEnergia',
        ),
        migrations.DeleteModel(
            name='Contiene',
        ),
    ]
