# Generated by Django 6.0.5 on 2026-05-19 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luminarias', '0003_rol_remove_contiene_red_remove_contiene_zona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crea',
            name='lectura',
            field=models.ForeignKey(db_column='id_lectura', on_delete=django.db.models.deletion.RESTRICT, to='Luminarias.registrarlectura'),
        ),
        migrations.AlterField(
            model_name='crea',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to='Luminarias.usuario'),
        ),
        migrations.AlterField(
            model_name='luminaria',
            name='red',
            field=models.ForeignKey(blank=True, db_column='id_red', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='luminarias', to='Luminarias.red'),
        ),
        migrations.AlterField(
            model_name='realiza',
            name='reporte',
            field=models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.RESTRICT, to='Luminarias.reporte'),
        ),
        migrations.AlterField(
            model_name='realiza',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to='Luminarias.usuario'),
        ),
        migrations.AlterField(
            model_name='registrarlectura',
            name='red',
            field=models.ForeignKey(blank=True, db_column='id_red', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lecturas', to='Luminarias.red'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='Luminarias.rol'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='municipio',
            field=models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='zonas', to='Luminarias.municipio'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='red',
            field=models.ForeignKey(blank=True, db_column='id_red', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='zonas', to='Luminarias.red'),
        ),
        migrations.AlterModelTable(
            name='crea',
            table='crea',
        ),
        migrations.AlterModelTable(
            name='luminaria',
            table='luminaria',
        ),
        migrations.AlterModelTable(
            name='municipio',
            table='municipio',
        ),
        migrations.AlterModelTable(
            name='realiza',
            table='realiza',
        ),
        migrations.AlterModelTable(
            name='red',
            table='red',
        ),
        migrations.AlterModelTable(
            name='registrarlectura',
            table='registrarlectura',
        ),
        migrations.AlterModelTable(
            name='reporte',
            table='reporte',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.AlterModelTable(
            name='zona',
            table='zona',
        ),
    ]
