# Generated by Django 6.0.5 on 2026-05-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luminarias', '0004_alter_crea_lectura_alter_crea_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
