# Generated by Django 6.0.5 on 2026-05-21 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luminarias', '0005_usuario_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, related_name='zonas_asignadas', to='Luminarias.usuario')),
                ('zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.RESTRICT, related_name='tecnicos_asignados', to='Luminarias.zona')),
            ],
            options={
                'db_table': 'asignacion_zona',
                'unique_together': {('usuario', 'zona')},
            },
        ),
    ]
