# Generated by Django 5.2.14 on 2026-05-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luminarias', '0006_asignacionzona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionzona',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
