# Generated by Django 5.2.1 on 2026-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luminarias', '0008_alter_asignacionzona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionzona',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
