# Generated by Django 6.0.4 on 2026-06-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luminarias', '0009_alter_asignacionzona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionzona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
