# Generated by Django 5.2.1 on 2026-06-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Luminarias', '0011_usuario_primer_acceso'),
        ('Luminarias', '0012_alter_asignacionzona_id'),
    ]

    operations = [
    ]
